const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'components', 'Tasks.jsx');
let content = fs.readFileSync(filePath, 'utf8');

const newStyles = `const styles = {
  // ── Unified System Tokens ──────────────────────────────────────────
  // Colors: Primary #5B5FFB, Text #1A1D20, Sub #6C7A87, Muted #9AA6B2, Border #E2E8F0
  // Radii: sm: 6px, md: 8px, lg: 12px, xl: 16px
  
  actionRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  tabToggle: {
    display: 'flex',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '4px',
  },
  toggleBtn: {
    background: 'none',
    border: 'none',
    padding: '6px 14px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#64748B',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap',
  },
  toggleBtnActive: {
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    fontWeight: '600',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  rightActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  epicFilterRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  epicFilterPill: {
    display: 'inline-flex',
    alignItems: 'center',
    border: '1px solid #E2E8F0',
    borderRadius: '20px',
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#475569',
    backgroundColor: '#FFFFFF',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  epicFilterPillActive: {
    backgroundColor: '#5B5FFB',
    color: '#FFFFFF',
    borderColor: '#5B5FFB',
  },
  headerSecondaryBtn: {
    background: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#0F172A',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    whiteSpace: 'nowrap',
    boxShadow: '0 1px 2px rgba(0,0,0,0.02)',
  },
  
  // ── Kanban Board ────────────────────────────────────────────────
  boardWrapper: {
    display: 'flex',
    gap: '24px',
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  kanbanGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '20px',
    flex: 1,
    height: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  kanbanColumn: {
    backgroundColor: '#F8FAFC',
    borderRadius: '16px',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minWidth: '280px',
    overflow: 'hidden',
    border: '1px solid #F1F5F9',
  },
  columnHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    padding: '0 4px',
    transition: 'background 0.2s ease',
  },
  columnHeaderWip: {
    backgroundColor: '#FEF9C3',
    padding: '8px 12px',
    borderRadius: '8px',
    marginLeft: '-8px',
    marginRight: '-8px',
  },
  columnTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  columnIndicatorDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#5B5FFB',
  },
  columnTitle: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#334155',
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  columnCount: {
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: '#E2E8F0',
    color: '#475569',
    padding: '2px 8px',
    borderRadius: '12px',
  },
  wipWarningBadge: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#B45309',
    cursor: 'help',
  },
  columnMenuBtn: {
    background: 'none',
    border: 'none',
    color: '#94A3B8',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px',
    borderRadius: '4px',
  },
  cardContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    flex: 1,
    overflowY: 'auto',
    paddingBottom: '16px',
  },
  taskCard: {
    padding: '16px',
    cursor: 'pointer',
    backgroundColor: '#FFFFFF',
    borderRadius: '12px',
    border: '1px solid #E2E8F0',
    boxShadow: '0 2px 8px rgba(15, 23, 42, 0.04)',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
  },
  epicPill: {
    display: 'inline-block',
    fontSize: '11px',
    fontWeight: '600',
    padding: '2px 10px',
    borderRadius: '6px',
    border: '1px solid',
    marginBottom: '10px',
  },
  storyPointsBadge: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#475569',
    backgroundColor: '#F1F5F9',
    borderRadius: '6px',
    padding: '2px 8px',
  },
  cardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  taskId: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#64748B',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#0F172A',
    marginBottom: '8px',
    lineHeight: '1.5',
  },
  cardDesc: {
    fontSize: '13px',
    color: '#475569',
    lineHeight: '1.5',
    marginBottom: '16px',
  },
  aiWarning: {
    backgroundColor: '#FEF2F2',
    color: '#B91C1C',
    padding: '6px 10px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '600',
    display: 'inline-flex',
    alignItems: 'center',
    marginBottom: '12px',
  },
  sprintChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    fontWeight: '500',
    color: '#475569',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '6px',
    padding: '4px 8px',
    marginBottom: '12px',
  },
  sprintChipIcon: {
    fontSize: '12px',
  },
  sprintChipStatus: {
    fontSize: '10px',
    fontWeight: '700',
    padding: '2px 6px',
    borderRadius: '4px',
    textTransform: 'uppercase',
  },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '12px',
    borderTop: '1px solid #F1F5F9',
  },
  cardAvatar: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '2px solid #FFFFFF',
  },
  commentsIndicator: {
    fontSize: '12px',
    color: '#94A3B8',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  dueDateText: {
    fontSize: '12px',
    color: '#64748B',
    fontWeight: '500',
  },
  columnAddBtn: {
    width: '100%',
    backgroundColor: 'transparent',
    border: '1px dashed #CBD5E1',
    borderRadius: '8px',
    color: '#64748B',
    fontSize: '13px',
    fontWeight: '600',
    padding: '12px',
    cursor: 'pointer',
    textAlign: 'center',
    transition: 'all 0.2s ease',
    marginTop: '8px',
  },

  // ── Sliding Panel ─────────────────────────────────────────────────
  slidingPanel: {
    position: 'absolute',
    top: 0, right: 0,
    width: '360px',
    height: '100%',
    zIndex: 30,
    padding: '24px',
    backgroundColor: '#FFFFFF',
    borderLeft: '1px solid #E2E8F0',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '-12px 0 40px rgba(15, 23, 42, 0.08)',
    overflowY: 'auto',
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
  },
  panelTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0F172A',
    lineHeight: '1.4',
  },
  panelCloseBtn: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    color: '#94A3B8',
    cursor: 'pointer',
    lineHeight: 1,
    flexShrink: 0,
    padding: '4px',
  },
  panelDesc: {
    fontSize: '14px',
    color: '#475569',
    lineHeight: '1.6',
    marginBottom: '20px',
  },
  divider: {
    height: '1px',
    backgroundColor: '#E2E8F0',
    margin: '20px 0',
  },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '20px 16px',
  },
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  metaLabel: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  metaVal: {
    fontSize: '13px',
    fontWeight: '500',
    color: '#0F172A',
  },
  metaValFlex: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#0F172A',
  },
  avatarMini: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  sectionHeader: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#334155',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    marginBottom: '12px',
  },
  panelComments: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    flex: 1,
    overflowY: 'auto',
    paddingRight: '4px',
  },
  panelCommentItem: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  commentContent: {
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    borderTopLeftRadius: '4px',
    padding: '12px 14px',
    flex: 1,
    fontSize: '13px',
    color: '#334155',
    lineHeight: '1.5',
  },
  commentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '6px',
    fontSize: '12px',
    color: '#64748B',
    fontWeight: '500',
  },

  // ── Backlog ───────────────────────────────────────────────────────
  backlogWrapper: {
    flex: 1,
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    padding: '4px',
  },
  backlogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backlogTitle: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: '4px',
  },
  backlogSubtitle: {
    fontSize: '14px',
    color: '#64748B',
  },
  backlogStat: {
    fontSize: '13px',
    color: '#475569',
    backgroundColor: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px 16px',
    fontWeight: '500',
  },
  backlogTable: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  backlogThead: {
    borderBottom: '1px solid #E2E8F0',
  },
  backlogTh: {
    padding: '12px 16px',
    fontSize: '11px',
    fontWeight: '600',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  backlogRow: {
    borderBottom: '1px solid #F1F5F9',
    cursor: 'grab',
    transition: 'background 0.2s ease',
  },
  backlogTd: {
    padding: '14px 16px',
    verticalAlign: 'middle',
    fontSize: '13px',
    color: '#1E293B',
    position: 'relative',
    fontWeight: '500',
  },
  dragHandle: {
    fontSize: '16px',
    color: '#CBD5E1',
    cursor: 'grab',
    userSelect: 'none',
    display: 'inline-block',
  },
  backlogTaskId: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#5B5FFB',
  },
  backlogTaskTitle: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#0F172A',
  },
  spBadge: {
    display: 'inline-block',
    minWidth: '28px',
    textAlign: 'center',
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: '#F1F5F9',
    color: '#475569',
    borderRadius: '6px',
    padding: '4px 8px',
  },
  ellipsisBtn: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    color: '#94A3B8',
    cursor: 'pointer',
    padding: '6px 8px',
    borderRadius: '6px',
    transition: 'background 0.2s ease',
  },
  ellipsisMenu: {
    position: 'absolute',
    right: '48px',
    top: '50%',
    transform: 'translateY(-50%)',
    backgroundColor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    boxShadow: '0 10px 30px rgba(15, 23, 42, 0.1)',
    zIndex: 100,
    minWidth: '220px',
    overflow: 'hidden',
  },
  ellipsisMenuItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    background: 'none',
    border: 'none',
    padding: '12px 16px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#334155',
    cursor: 'pointer',
    transition: 'background 0.2s ease',
  },
  inlineCreateRow: {
    borderBottom: '1px solid #E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  inlineInput: {
    flex: 1,
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '13px',
    color: '#0F172A',
    outline: 'none',
    backgroundColor: '#FFFFFF',
    minWidth: '240px',
    transition: 'border-color 0.2s',
  },
  inlineAddBtn: {
    backgroundColor: '#5B5FFB',
    color: '#FFF',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'background 0.2s',
  },
  inlinePointsSelect: {
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px',
    fontSize: '13px',
    color: '#475569',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    width: '70px',
  },

  // ── Modals (Sprint Complete, Task, Epic, Sprint) ────────────────
  sprintCompleteWarning: {
    backgroundColor: '#FEF9C3',
    border: '1px solid #FEF08A',
    borderRadius: '12px',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  warningRow: {
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
  },
  warningIcon: {
    fontSize: '24px',
    color: '#B45309',
    flexShrink: 0,
    marginTop: '2px',
  },
  warningTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#713F12',
    marginBottom: '6px',
  },
  warningDesc: {
    fontSize: '13px',
    color: '#92400E',
    lineHeight: '1.5',
  },
  modalContent: {
    maxWidth: '520px',
    borderRadius: '16px',
  },
  modalHeader: {
    padding: '24px 32px 20px 32px',
    borderBottom: '1px solid #F1F5F9',
    position: 'relative',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#0F172A',
    display: 'flex',
    alignItems: 'center',
  },
  modalCloseBtn: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    background: 'none',
    border: 'none',
    fontSize: '24px',
    color: '#94A3B8',
    cursor: 'pointer',
    padding: '4px',
    lineHeight: 1,
    transition: 'color 0.2s',
  },
  modalForm: {
    padding: '24px 32px 32px 32px',
  },
  row: {
    display: 'flex',
    gap: '16px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
  },
  discardBtn: {
    background: 'none',
    border: 'none',
    color: '#64748B',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    padding: '10px 16px',
    borderRadius: '8px',
    transition: 'background 0.2s',
  },
  
  // ── Color Picker ──────────────────────────────────────────────────
  colorPickerWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  colorSwatchGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(8, 1fr)',
    gap: '10px',
  },
  colorSwatch: {
    width: '100%',
    aspectRatio: '1/1',
    borderRadius: '8px',
    border: '2px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    padding: 0,
  },
  colorSwatchActive: {
    boxShadow: '0 0 0 2px #FFFFFF, 0 0 0 4px #0F172A',
  },
  hexInputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginTop: '8px',
  },
  hexInput: {
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '13px',
    color: '#0F172A',
    fontFamily: 'monospace',
    width: '120px',
    outline: 'none',
    backgroundColor: '#FFFFFF',
    transition: 'border-color 0.2s',
  },
  
  // ── Gradient pill button for epic ─────────────────────────────────
  gradientPillBtn: {
    color: '#FFFFFF',
    border: 'none',
    fontFamily: 'var(--font-sans)',
    fontWeight: '600',
    fontSize: '14px',
    padding: '12px 28px',
    borderRadius: '100px',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    boxShadow: '0 4px 14px rgba(91, 95, 251, 0.25)',
  },
  
  // ── Sprint date presets ───────────────────────────────────────────
  presetRow: {
    display: 'flex',
    gap: '10px',
  },
  presetBtn: {
    background: '#F8FAFC',
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#475569',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  sprintHeaderBar: {}, sprintLeft: {}, sprintLabel: {}, sprintName: {}, sprintDates: {}, sprintRight: {}, sprintGoalLabel: {}, sprintGoal: {}, sprintStats: {}, sprintStat: {}, sprintStatVal: {}, sprintStatLabel: {}
};`;

const startIndex = content.indexOf('const styles = {');
const endIndex = content.lastIndexOf('};');

if (startIndex !== -1 && endIndex !== -1) {
  content = content.substring(0, startIndex) + newStyles + content.substring(endIndex + 2);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Successfully updated styles object.');
} else {
  console.log('Could not find styles object bounds.');
}
